name: Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    environment: BUZZ_GH_TOKEN
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'true'
        token: ${{ secrets.my_pat }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      env:
        BUZZ_GH_TOKEN: ${{ secrets.BUZZ_GH_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip install -e .

    - name: Testing the code with black, flake8, and unit tests
      run: |
        black .
        flake8 .
        pytest tests
